version: "3"  # optional since v1.27.0
services:
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`dasbord.passebem.tk`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"